### ISSUE TITLE
Failed to run ios

### ISSUE THREAD

**Issue by yuvalsuede** [bberak/react-native-game-engine-handbook#15]
Unable to resolve "scheduler/tracing" from "node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js"
Failed building JavaScript bundle.

**Comment by bberak** [comment]
Hi @yuvalsuede,

Are you running this via the Expo app?

**Comment by bberak** [comment]
Hi @yuvalsuede,

I've just updated the app to work with the latest version of Expo. Hopefully this will fix your issue too. Upgrade steps:

```
cd react-native-game-engine-handbook
rm -rf node_modules
git pull
npm install -g expo-cli
npm install
npm run start
# You might also need to update the Expo client on your devices
```

If it helps, I'm running the following versions:

```
node -v: v12.13.0
npm -v: 6.12.0
expo --version: 3.21.13
```

Let me know how that goes, cheers!

**Comment by bberak** [comment]
Hi @yuvalsuede,

I'm closing this issue for now, but please feel free to re-open it if necessary. Cheers!
