### ISSUE TITLE
SDK 33 is not supported anymore

### ISSUE THREAD

**Issue by BorisB** [bberak/react-native-game-engine-handbook#17]
Can you please update app to support actual SDK?

**Comment by bberak** [comment]
Hi @BorisB,

I'll try update the app to use the latest version of Expo SDK today or tomorrow..

**Comment by bberak** [comment]
Hi @BorisB ,

I've just updated the app to work with the latest version of Expo. Upgrade steps:

```
cd react-native-game-engine-handbook
rm -rf node_modules
git pull
npm install -g expo-cli
npm install
npm run start
```

If it helps, I'm running the following versions:

```
node -v: v12.13.0
npm -v: 6.12.0
expo --version: 3.21.13
```

Let me know how that goes, cheers!

**Comment by rafaelmaeuer** [comment]
Same problem exists now for deprecation of SDK 38, update to v39 is required

**Comment by bberak** [comment]
Thanks for the heads-up @rafaelmaeuer - I'll upgrade it now..

**Comment by bberak** [comment]
Okay @rafaelmaeuer, should be updated now, cheers!
