### ISSUE TITLE
Suggestion: Include an already linked iOS & Android project

### ISSUE THREAD

**Issue by itchingpixels** [bberak/react-native-game-engine-handbook#2]
Hi!

I'd love to try this out - we've bumped into performance issues while using react-game-kit, and switching over to react-native-game-engine would be an option.

But unfortunately I have been bumping into issues trying to compile this project, first, the one there's already a closed issue about (although it doesn't seem to be solved), and now I'm getting another error

I think simply committing the linked Android & iOS projects would help greatly in resolving these, especially if this repo serves demonstrational purposes.

**Comment by bberak** [comment]
Hi @itchingpixels,

Yep good call - I'll link the Android projects properly and commit fix (I'll do my best to get this into the repo tonight). That said, the iOS project should be linked properly, I'm running it on my device now (maybe I need to re-clone to reproduce this problem).

In the mean time, as a work around, if you don't need the WebGL examples, you can try revert to commit 9530cbbf86cacc24a4603d373d249342f931ed7c and run from there.

Cheers.

**Comment by bberak** [comment]
Hi @itchingpixels,

Can you try deleting the project and cloning again? I've pushed a linked version of the android build files which I'm hoping will solve most of these issues.

You will need install and set the Android NDK path (if not already installed) - instructions are in the README file. Everything else should be good to go, fingers crossed.

I'm getting OKAY performance in the Android simulator (although the OpenGL examples are really fluid). I'll be interested to hear if you get better performance on a physical device (I've left my Samsung tablet at work so cannot test this right now).

Let me know how it goes, cheers.

**Comment by itchingpixels** [comment]
An irrelevant note that may help others: we were investigating react-native-game-engine because we wanted to validate the hyptohesis that react-game-kit is the culrpit, but the performance problems visible on Android come from matter-js. Unfortunately now we're migrating over to box2dweb, which is sad, because the API is close to horrible.
