### ISSUE TITLE
Operator 'abs' not found

### ISSUE THREAD

**Issue by sheminusminus** [bberak/react-native-game-engine-handbook#21]
Currently, on a fresh clone, there's an error on initial launch, `Operator 'abs' not found`.

Running:

- macOS Catalina 10.15.5
- Expo 4.0.13
- iOS 13.4.1
- iPhone X

It looks like it might be some issue with the code here, and the underlying native modules, but I'm not totally sure. Here's the screenshot:

![IMG_5323](https://user-images.githubusercontent.com/9907610/102008235-f1fc0400-3ce3-11eb-9a3e-3112cedab0e1.PNG)

**Comment by sheminusminus** [comment]
Update: I was able to fix this by updating to the following package versions:

```
"expo": "40.0.0",
"expo-camera": "9.1.0",
"expo-gl": "9.2.0",
"expo-linear-gradient": "8.4.0",
...
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
```

(I'm not sure if the camera, gl, or gradient packages were necessary to update at all, but in my own personal experience, when updating one expo thing, it's usually better to update all the expo things, so  ¯\\\_(ツ)_/¯ )

**Comment by bberak** [comment]
Hmmm how odd @sheminusminus - I merged a small PR about two weeks ago and tested via a fresh clone.. 

Thanks for the bug report and fix.. I'll try to updgrade to Expo SDK 40 and apply the updates you listed (totally agree, probably easiest to be liberal with the updates).

Thanks again!

**Comment by SRochas** [comment]
@bberak I'd be willing to make this change if you provided me permission to create a branch / open a PR.

**Comment by bberak** [comment]
I've just updated the app to use Expo SDK 42 and can confirm that it is running on both Android and iOS. Please feel free to re-open this issue if necessary, cheers!
