### ISSUE TITLE
Support for Expo SDK  44, 45, 46

### ISSUE THREAD

**Issue by c0cumm01** [bberak/react-native-game-engine-handbook#39]
any way we can get this repo upgraded for Expo SDK 44 or 45 or 46? would greatly appreciate it

**Comment by bberak** [comment]
Hey @c0cumm01,

Apologies -- I'm a bit swamped with work at the moment. 

Always happy to accept a PR if this is something you might be comfortable with attempting. The `expo-cli` used to have a command for upgrading SDKs (hopefully that is still the case 🤞).

**Comment by bberak** [comment]
Hey @c0cumm01,

@matthops has just added support for Expo SDK 46 (I've tried it and it's working )
