### ISSUE TITLE
Can't get up and running on iOS Simulator.

### ISSUE THREAD

**Issue by xpol** [bberak/react-native-game-engine-handbook#4]
Clone project follow the doc, fail to build.
Then upgrade react-native to 0.56.0, it builds, but fail to run, the app crash at startup.
Then upgrade all to latest with yarn upgrade --latest, same as above.

**Comment by bberak** [comment]
Hi @xpol,

I've updated some dependencies and verified that the app works on my simulator. I'm running node 8.9.4 and npm 5.6.0

Give the following another shot, I'm hopeful you'll have better restuls

```
git clone https://github.com/bberak/react-native-game-engine-handbook.git

cd react-native-game-engine-handbook

npm install

react-native link

react-native run-ios --configuration Release
```
Feel free to reopen this issue if you're still having problems.

Cheers

**Comment by xpol** [comment]
Thank you very much!
Boris Berak <notifications@github.com>于2018年9月16日 周日上午12:50写道：
