### ISSUE TITLE
No bundle URL present - Cannot run the project

### ISSUE THREAD

**Issue by giulioambrogi** [bberak/react-native-game-engine-handbook#5]
I've cloned the project and followed the steps to run it on iOS simulator.
```
git clone https://github.com/bberak/react-native-game-engine-handbook.git

cd react-native-game-engine-handbook

npm install

react-native link

react-native run-ios
```

Unfortunately I'm getting the following error:

```No bundle URL present

Make sure you're running a package server or have included a .jsbundle file in your application bundle.
```

Node version: 8.12.0
Npm version: 6.4.1

**Comment by bberak** [comment]
Thanks for the heads up @giulioambrogi - I'll try investigate tonight after work. Cheers.

**Comment by bberak** [comment]
Sorry for the late reply @giulioambrogi 

I wasn't able to reproduce your error, however my Node version is **8.9.4** and my Npm version is **5.6.0**

I have committed my **package-lock.json** file however. Would you be able to pull the repo, clear your **node_modules** and try again? Cheers.

**Comment by giulioambrogi** [comment]
Hi @bberak, Thank you for your answer.

I can't reproduce the issue anymore, I'm on a different laptop though. So I guess it was sth with my environment then.

Thank you
