### ISSUE TITLE
Could not determine java version from '10.0.2'

### ISSUE THREAD

**Issue by BrianD91** [bberak/react-native-game-engine-handbook#8]
I'm trying to execute `react-native run-android` but I am encountering the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.2'.
```

Running:
>Kubuntu 18.04
>Node 8.10.0
>NPM 6.4.1
>OpenJDK 10.0.2

**Comment by BrianD91** [comment]
Update, I was able to ameliorate *that* error message with the following fix:
```
Edit the file ~/android/gradle/wrapper/gradle-wrapper.properties and update the last line with:

distributionUrl=https\://services.gradle.org/distributions/gradle-4.3-rc-2-all.zip
```

However,  now I'm encountering a different error:

```
*What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
    > javax/xml/bind/annotation/XmlSchema
```

**Comment by BrianD91** [comment]
Sorry, that should say the new error is:

```
* What went wrong:
> Failed to notify project evaluation listener.
    > Could not initialize class com.android.sdklib.repository.AndroidSdkHandler
```

**Comment by BrianD91** [comment]
Resolved by installing openJDK 8 and setting that as the default.

**Comment by bberak** [comment]
Woah @BrianD91 - thanks for debugging and resolving that issue. I'm sure that will help others running non-Windows/non-Mac operating system. Much appreciated!
